USE [master]
GO

/****** Object:  Database [CodeChallenge]    Script Date: 17/03/2023 17:55:52 ******/
CREATE DATABASE [CodeChallenge]
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CodeChallenge].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CodeChallenge] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CodeChallenge] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CodeChallenge] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CodeChallenge] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CodeChallenge] SET ARITHABORT OFF 
GO

ALTER DATABASE [CodeChallenge] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CodeChallenge] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CodeChallenge] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CodeChallenge] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CodeChallenge] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CodeChallenge] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CodeChallenge] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CodeChallenge] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CodeChallenge] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CodeChallenge] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CodeChallenge] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CodeChallenge] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CodeChallenge] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CodeChallenge] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CodeChallenge] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CodeChallenge] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CodeChallenge] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CodeChallenge] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CodeChallenge] SET  MULTI_USER 
GO

ALTER DATABASE [CodeChallenge] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CodeChallenge] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CodeChallenge] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CodeChallenge] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CodeChallenge] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CodeChallenge] SET QUERY_STORE = OFF
GO

USE [CodeChallenge]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [CodeChallenge] SET  READ_WRITE 
GO

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT

BEGIN TRANSACTION
GO
CREATE TABLE dbo.Director
	(
	uuid uniqueidentifier NOT NULL,
	name nvarchar(50) NOT NULL,
	birthdate datetime NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Director ADD CONSTRAINT
	PK_Director PRIMARY KEY CLUSTERED 
	(
	uuid
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.Director SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

BEGIN TRANSACTION
GO
CREATE TABLE dbo.Movie
	(
	uuid uniqueidentifier NOT NULL,
	title nvarchar(50) NOT NULL,
	director_uuid uniqueidentifier NOT NULL,
	release_date datetime NOT NULL,
	rating smallint NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Movie ADD CONSTRAINT
	PK_Movie PRIMARY KEY CLUSTERED 
	(
	uuid
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.Movie ADD CONSTRAINT
	FK_Movie_Director FOREIGN KEY
	(
	director_uuid
	) REFERENCES dbo.Director
	(
	uuid
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.Director SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

INSERT dbo.Director ([uuid], [name], [birthdate]) VALUES (N'7a2799ea-2176-4b81-a1e4-0026926e6257', N'Tan', CAST(N'2001-06-18T09:34:38.490' AS DateTime))
INSERT dbo.Director ([uuid], [name], [birthdate]) VALUES (N'93c121d7-8faf-429b-88ec-44a8d2880c49', N'Phuc', CAST(N'2000-06-18T09:34:38.490' AS DateTime))

INSERT dbo.Movie ([uuid], [title], [director_uuid], [release_date], [rating]) VALUES (N'4efb5ac6-9e64-40cf-86d7-07b568e8289a', N'Task 1', N'7a2799ea-2176-4b81-a1e4-0026926e6257', CAST(N'2021-07-18T09:34:38.490' AS DateTime), 8)
INSERT dbo.Movie ([uuid], [title], [director_uuid], [release_date], [rating]) VALUES (N'bfd76029-a4a4-4cdf-a836-449aa7b5e844', N'Task 2', N'7a2799ea-2176-4b81-a1e4-0026926e6257', CAST(N'2020-07-18T09:34:38.490' AS DateTime), 3)
INSERT dbo.Movie ([uuid], [title], [director_uuid], [release_date], [rating]) VALUES (N'a334310b-7112-479c-9c1c-20b4068e27f2', N'Task 3', N'93c121d7-8faf-429b-88ec-44a8d2880c49', CAST(N'2019-07-18T09:34:38.490' AS DateTime), 4)